language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install: "pip install nose coverage python-coveralls"
script: nosetests --with-coverage --cover-html --cover-html-dir=coverage
after_success:
  - coveralls
